parameters:
#    bug_tracker_project.example.class: BugTracker\ProjectBundle\Example

services:
#    bug_tracker_project.example:
#        class: %bug_tracker_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
