<?php

namespace PhiTrac\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findAllAlphabetical()
    {
        return $this->_em->createQueryBuilder()
                    ->select('a')
                    ->from('PhiTracUserBundle:User', 'a')
                    ->orderBy('a.name')
                    ->getQuery()
                    ->getResult();
    }
}
