<?php

namespace PhiTrac\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function findAllAlphabetical()
    {
        return $this->_em->createQueryBuilder()
                    ->select('a')
                    ->from('PhiTracProjectBundle:Project', 'a')
                    ->orderBy('a.name')
                    ->getQuery()
                    ->getResult();
    } 
}
