<?php

namespace PhiTrac\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;
use PhiTrac\UserBundle\Entity\User;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function findAllAlphabetical()
    {
        return $this->_em->createQueryBuilder()
                    ->select('a')
                    ->from('PhiTracProjectBundle:Project', 'a')
                    ->orderBy('a.name')
                    ->getQuery()
                    ->getResult();
    }

    public function findProjectWhereUserIsMember(User $user)
    {
        return $this->createQueryBuilder('p')
                    ->join('p.members', 'm', 'WITH', 'm.id = :id')
                    ->addSelect('m')
                    ->getQuery()
                    ->setParameter('id', $user->getId())
                    ->getResult();
    } 
}
