parameters:
#    phi_trac_user.example.class: PhiTrac\UserBundle\Example

services:
#    phi_trac_user.example:
#        class: %phi_trac_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
